
---

- name: Check if domain wordpress is needed for this host
  ansible.builtin.include_tasks: create.yml
  when: inventory_hostname == subdomain.wordpress_host
  loop: "{{ domain.subdomains }}"
  loop_control:
    loop_var: subdomain
