
---

- name: Check if domain wordpress database is needed for this host
  ansible.builtin.include_tasks: create.yml
  when: inventory_hostname == subdomain.wordpress_database_host
  loop: "{{ domain.subdomains }}"
  loop_control:
    loop_var: subdomain
