
---

- name: Check if domain reverse proxy is needed for this host
  ansible.builtin.include_tasks: create.yml
  when: inventory_hostname == subdomain.reverse_proxy_host
  loop: "{{ domain.subdomains }}"
  loop_control:
    loop_var: subdomain
