# Update exim4 configuration

---

  - name: Template out the Exim4 update-exim4.conf.conf file
    template:
      src: update-exim4.conf.conf.j2
      dest: /etc/exim4/update-exim4.conf.conf
    notify:
      - Run update-exim4.conf
    become: yes
