- name: Deploy wordpress host role
  become: yes
  block:

    - name: Install apt package(s) for wordpress host role
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - php
          - php-mysql

    - name: Enable apache2 rewrite module
      apache2_module:
        state: present
        name: rewrite

    # TODO: Check if task is necessary
    # This directory isn't present on multiple Apache webservers that I have
    # in current use so I wonder if perhaps it isn't needed.
    #- name: Create apache2 run directory
    #  file:
    #    path: /var/run/apache2
    #    state: directory

    - name: Change ports that apache2 will listen on
      template:
        src: ports.conf.j2
        dest: /etc/apache2/ports.conf
        mode: '755'

    - name: Install WP-CLI
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: '755'
