- name: Enable dynamic DNS service on gateway server
  become: yes
  block:

    - name: Install Perl packages used by the dynamic-dns script
      apt:
        name:
          - libjson-perl
          - libperl5.28
          - libwww-perl

    - name: deploy the dynamic-dns script
      template:
        src: dynamic-dns.j2
        dest: /usr/local/sbin/dynamic-dns
        mode: 0755

    - name: add crontab entries
      cron:
        job: /usr/local/sbin/dynamic-dns
        minute: "{{ item }}"
        name: "Dynamic DNS {{ item }}"
      with_items:
        - 0
        - 15
        - 30
        - 45
