- name: Deploy dynamic DNS role
  become: yes
  block:

    - name: Install APT packages used by the dynamic DNS role
      ansible.builtin.apt:
        name:
          - cron
          - libjson-perl
          - libperl5.32
          - libwww-perl

    - name: Deploy the dynamic-dns script
      ansible.builtin.template:
        src: dynamic-dns.j2
        dest: /usr/local/sbin/dynamic-dns
        mode: 0755

    - name: Add crontab entries for the dynamic-dns script
      ansible.builtin.cron:
        job: /usr/local/sbin/dynamic-dns
        minute: "{{ item }}"
        name: "Dynamic DNS {{ item }}"
      with_items:
        - "0"
        - "15"
        - "30"
        - "45"
