# Deploy email external role

---

- name: Copy id_rsa.pub from dns-api host to authorized_keys
  ansible.builtin.lineinfile:
    path: ~/.ssh/authorized_keys
    line: "{{ lookup('file', 'files/id_rsa.pub') }}"
    create: yes

- block:

    - name: Import the Dovecot aspects of the email role
      ansible.builtin.import_role:
        name: email
        handlers_from: dovecot
        tasks_from: dovecot

    - name: Install APT package(s) required by the email external role
      # The base email role installs the dovecot-imapd and exim4 pacakges but
      # the email external role requires additional/different packages as
      # follows:
      #  - The dovecot-lmtpd package is required so that we can use the sieve
      #    mail plugin to filter spam messages automatically.
      #  - The dovecot-sieve package provides the Dovecot Sieve plugin to
      #    provide mail filtering facilities at the time of final message
      #    delivery, which we use to filter spam.
      #  - The exim4-daemon-heavy package replaces the exim4 package for access
      #    to the Dovecot authentication drivers.
      ansible.builtin.apt:
        name:
          - dovecot-lmtpd
          - dovecot-sieve
          - exim4-daemon-heavy
        install_recommends: no

    - name: Configure email authentication to our specific needs
      ansible.builtin.import_tasks: auth.yml

    - name: Configure sieve email filtering to our specific needs
      ansible.builtin.import_tasks: sieve.yml

    - name: Modify Exim to use different smarthosts depending on sender domain
      ansible.builtin.import_tasks: smarthosts.yml

    - name: Copy the config header
      ansible.builtin.copy:
        src: config-header
        dest: /etc/exim4/conf.d/main/00_exim4-config_header
      notify:
        - exim configuration changed

    - name: Add TLS_ON_CONNECT_PORTS section to config template
      ansible.builtin.blockinfile:
        path: /etc/exim4/conf.d/main/03_exim4-config_tlsoptions
        insertafter: '^\.ifdef MAIN_TLS_ENABLE$'
        block: |-
          .ifdef TLS_ON_CONNECT_PORTS
            tls_on_connect_ports = TLS_ON_CONNECT_PORTS
          .endif
      notify:
        - exim configuration changed

  become: yes
