- name: Deploy the email external role
  become: yes
  block:

    - name: Install apt package(s) required by the email external role
      apt:
        name:
          - dovecot-imapd
          - exim4
        install_recommends: no

    # Boolean values are provided as strings to mitigate this issue:
    # https://github.com/ansible/ansible/issues/25481
    # Not sure that the vtype specified has any effect?
    # Only options where a value is needed that is different to the default are
    # set.
    - name:
      debconf:
        name: exim4-config
        question: "{{ item.question }}"
        value: "{{ item.value }}"
        vtype: "{{ item.vtype }}"
      loop:
        # Use chosen email gateway provider to send.
        # Receive via SMTP as externally facing MX host.
        - question: exim4/dc_eximconfig_configtype
          value: mail sent by smarthost; received via SMTP or fetchmail
          vtype: select
        # Prefer Maildir rather than mbox for local delivery.
        - question: exim4/dc_localdelivery
          value: Maildir format in home directory
          vtype: select
        # Set the system mail name to the domain of the host.
        - question: exim4/mailname
          value: varilink.co.uk
          vtype: string
        # Listen on external interface for incoming SMTP connections.
        - question: exim4/dc_local_interfaces
          value:
          vtype: string
        # Identify of external email gateway provider.
        - question: exim4/dc_smarthost
          value: "{{ email_external_gateway }}"
          vtype: string
        # Don't hide local mail name in outgoing mail.
        - question: exim4/hide_mailname
          value: "false"
          vtype: boolean
        # Use split configuration files.
        - question: exim4/use_split_config
          value: "true"
          vtype: boolean
        # Set the postmaster email address.
        # TODO: Parameterise
        # This email address is public knowledge however it should be
        # parameterised.
        - question: exim4/dc_postmaster
          value: david.williamson@varilink.co.uk
          vtype: string
