# Restart the radicale service to reflect a change to its configuration.
# NOTE: There is no reload option for the radicale service.

---

- block:

  - name: Determine current status of the Radicale service
    service_facts:
    listen: "Restart radicale"

  - name: Restart Radicale if it is running
    service:
      name: radicale
      state: restarted
    when: ansible_facts['services']['radicale']['state'] == 'running'
    listen: "Restart radicale"

  become: yes
